spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: eureka-client1

server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka/
